"""empty message

Revision ID: 052072266c3c
Revises: 
Create Date: 2022-07-10 23:03:43.147558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '052072266c3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idrref', sa.String(length=16), nullable=True),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('sum', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('confirmation_status', sa.Enum('undefined', 'confirmed', 'rejected', name='confirmationstatus'), nullable=True),
    sa.Column('confirmation_date', sa.DateTime(), nullable=True),
    sa.Column('responsible_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['responsible_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idrref')
    )
    op.create_index(op.f('ix_documents_timestamp'), 'documents', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_timestamp'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
