"""empty message

Revision ID: a9426647feec
Revises: 052072266c3c
Create Date: 2022-07-11 09:58:49.222181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9426647feec'
down_revision = '052072266c3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('code', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'code')
    # ### end Alembic commands ###
